database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "exampledb"
  sslmode: "disable"
  max_idle_conns: 15
  max_open_conns: 100
  conn_max_life_time: "5m"

http:
  host: "0.0.0.0"
  port: 8080

logging:
  filePath: "../../logs/"
  encoding: "json"
  level: "debug"
  logger: "zap"
        
jwt:
  secret_key: "supersecretkey1234567890abcdefghijklmnopqrstuvwxyz!"
  expire_minutes: 60

email:
  smtp_server: "smtp.gmail.com"
  smtp_port: "587"
  smtp_user: "fkz761997@gmail.com"
  smtp_pass: "teyh uhya ilwx ljou"
  from_email: "fkz761997@gmail.com"
    
